CREATE TABLE STUDENTDETAIL
(
FIRSTNAME varchar2(50) NOT NULL,
LASTNAME varchar2(50) NOT NULL,
STUDENTGENDER varchar2(20) NOT NULL,
COLLEGEID varchar2(50) NOT NULL,
STUDENTEMAIL varchar2(50) NOT NULL,
STUDENTBRANCH varchar2(50) NOT NULL,
ADDRESSLINE1 varchar2(100) NOT NULL,
ADDRESSLINE2 varchar2(100) NOT NULL,
CITY varchar2(50) NOT NULL,
STATE varchar2(50) NOT NULL,
PINCODE varchar2(20) NOT NULL,
STUDENTPHONE varchar2(20) NOT NULL,
STUDENTPERCENTMARKS FLOAT NOT NULL,
STUDENTPASSWORD varchar2(50) NOT NULL
);